[profile.default]

optimizer_runs = 9999999
via_ir = true
out = "build/out"
cache_path = "build/cache"
fs_permissions = [{ access = "read", path = "./"}]

[fmt]

line_length = 80
tab_width = 4
bracket_spacing = true