[profile.default]

solc = '0.8.26'
optimizer_runs = 200
out = "build/out"
via_ir = true
cache_path = "build/cache"
fs_permissions = [{ access = "read", path = "./"}]

remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "erc4626-tests/=lib/openzeppelin-contracts/lib/erc4626-tests/",
    "forge-std/=lib/forge-std/src/",
    "halmos-cheatcodes/=lib/openzeppelin-contracts/lib/halmos-cheatcodes/src/",
    "openzeppelin-contracts/=lib/openzeppelin-contracts/",
    "@/=src/"
]
